version: "3.7"

services:

  mongodb:
    image: "mongo:7"
    hostname: "mongodb"
    restart: "no"
    ports:
      - 27019:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
